language: android

android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-27.0.3
    - android-27

    # Support library
    - extra-android-support
    - extra-android-m2repository
    
script:
- chmod +x ./gradlew